---
title: "Covid-19 10/07/2020"
output:
  html_document: default
  pdf_document: 
    fig_width: 7
    fig_height: 6
classoption: landscape
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(gridExtra)
library(tidyr)    
library(ggplot2)   
library(readxl)
library(dplyr)
library(geobr)


corona = read.csv("C:\\Users\\bispo\\Downloads\\covid2.csv")
states <- read_state(year=2014)

no_axis <- theme(axis.title=element_blank(),axis.text=element_blank(),axis.ticks=element_blank())
```


## Número de pessoas diagnosticadas com Covid-19 no Brasil


```{r g3,warning=FALSE,message= FALSE,error=FALSE,cache=FALSE}

populacao <- corona %>% group_by(estado) %>% summarise(populacao = max(populacaoTCU2019[is.finite(populacaoTCU2019)]))
n_obitos_estado <- corona %>% group_by(estado) %>% summarise(obitos_uf = max(obitosAcumulado))
n_obitos_cidade <- corona %>% group_by(municipio) %>% summarise(obitos_cit = max(obitosAcumulado))

n_casos_estado <- corona %>% group_by(estado) %>% summarise(casos_uf = max(casosAcumulado))
n_casos_cidade <- corona %>% group_by(municipio) %>% summarise(casos_cit = max(casosAcumulado))

states <- left_join(states,n_obitos_estado,by=c("abbrev_state"= "estado"))
states <- left_join(states,n_casos_estado,by=c("abbrev_state"= "estado"))
states <- left_join(states,populacao,by=c("abbrev_state"= "estado"))

states1 <- states  %>% mutate(obitos_x_pop = obitos_uf/populacao*100,casos_x_pop = casos_uf/populacao*100,obito_x_covid= obitos_uf/casos_uf)


ggplot() + 
  geom_sf(data=states1,aes(fill=casos_uf),color="black",size=.05)+
  scale_fill_distiller(direction = 1,palette = "Greens", name="",breaks = c(100000,150000,200000,250000,300000,350000))+
  theme_minimal() +no_axis+
  guides(fill = guide_colourbar(barwidth = 2, barheight = 25))+ geom_sf_text(data=states1,aes(label = abbrev_state))

```





## Porcentagem de pessoas diagnosticadas com Covid-19 em relação à população estadual


```{r g4, warning=FALSE}
ggplot() + 
  geom_sf(data=states1,aes(fill=casos_x_pop),color="black",size=.05)+
  scale_fill_distiller(direction = 1,palette = "Greens", name="",breaks = c(0.5,1,1.5,2,2.5,3,3.5))+
  theme_minimal() +no_axis+
  guides(fill = guide_colourbar(barwidth = 2, barheight = 25))+ geom_sf_text(data=states1,aes(label = abbrev_state))


```





## Número óbitos por Covid-19 no Brasil


```{r g1,warning=FALSE,message= FALSE,error=FALSE,cache=FALSE}



ggplot() + 
  geom_sf(data=states1,aes(fill=obitos_uf),color="black",size=.05)+
  scale_fill_distiller(direction = 1,palette = "OrRd", name=" ",breaks = c(5000,10000,15000,20000))+
  theme_minimal() +no_axis+
  guides(fill = guide_colourbar(barwidth = 2, barheight = 25))+ geom_sf_text(data=states1,aes(label = abbrev_state))




```





## Porcentagem de óbitos por Covid-19 em relação à população estadual


```{r g2,warning=FALSE}

ggplot() + 
  geom_sf(data=states1,aes(fill=obitos_x_pop),color="black",size=.05)+
  scale_fill_distiller(direction = 1,palette = "OrRd", name=" ")+
  theme_minimal() +no_axis+
  guides(fill = guide_colourbar(barwidth = 2, barheight = 25))+ geom_sf_text(data=states1,aes(label = abbrev_state))
```





## Porcentagem de pessoas diagnosticadas com Covid-19 que foram a óbito


```{r g5, warning=FALSE}
ggplot() + 
  geom_sf(data=states1,aes(fill=obito_x_covid*100),color="black",size=.05)+
  scale_fill_distiller(direction = 1, name="")+
  theme_minimal() +no_axis+
  guides(fill = guide_colourbar(barwidth = 2, barheight = 25))+ geom_sf_text(data=states1,aes(label = abbrev_state))


```


